change from housepower to clickhouse
ClickHouse/spark-clickhouse-connector pull request #328
Opened 2024-06-30 08:25 UTC by mzitnik

2024-07-01 02:25 UTC, pan3793 commented on gradle.properties
> +
nit: unnecessary changes.

2024-07-01 02:25 UTC, pan3793 commented on gradle.properties
>  mavenCentralMirror=https://mirrors.cloud.tencent.com/nexus/repository/maven-public/
Gradle does not have a built-in Repo Mirror setting like Maven does, we have to explicitly expose a variable. We can keep it with the default value `https://repo1.maven.org/maven2/`. Users can override this variable in `$HOME/.gradle/gradle.properties`

2024-07-01 02:25 UTC, pan3793 commented on build.gradle
> +        mavenCentral()
ditto, would like to keep it

2024-07-01 02:25 UTC, pan3793 commented on .github/workflows/publish-snapshot.yml
>            -PmavenPassword='${{ secrets.NEXUS_PW }}'
I suppose you have set these secrets properly, right?

2024-07-01 02:25 UTC, pan3793 commented on .github/workflows/publish-release.yml
>            -Psigning.gnupg.keyName='Cheng Pan'
a new PGP key should be generated and set properly

2024-07-01 13:44 UTC, Old177 requested changes
Leav

2024-07-01 13:47 UTC, Old177 requested changes
The

2024-07-01 13:49 UTC, pan3793 commented
@Old177 do you have any questions? please stop creating spam comments/issues

2024-07-01 13:52 UTC, Old177 requested changes
U

2024-07-03 09:41 UTC, pan3793 commented on gradle.properties
> +
```suggestion
```

2024-07-03 09:42 UTC, pan3793 commented on build.gradle
> +        mavenCentral()
```suggestion
        maven { url = "$mavenCentralMirror" }
```

2024-07-03 09:43 UTC, pan3793 approved these changes
I'm fine with the existing changes, but I suppose additional changes are required to make the release happy.

2024-07-03 13:09 UTC, mshustov approved these changes

2024-07-03 13:09 UTC, merged